language: go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq zlib1g-dev build-essential libssl-dev libbz2-dev libpcre3-dev yasm automake autoconf cmake libjpeg-turbo8-dev libtheora-dev libvorbis-dev libvpx-dev libx264-dev libvlccore-dev libvlc-dev libavdevice-dev libavdevice53 mediainfo 2>&1 > /dev/null
  - git clone -b n3.0 --depth=1 git://source.ffmpeg.org/ffmpeg.git
  - cd ffmpeg
  - ./configure --enable-shared --enable-swscale --enable-gpl  --enable-libx264 --enable-libvpx --enable-libvorbis --enable-libtheora
  - make -j `grep processor /proc/cpuinfo|wc -l`
  - sudo make install
  - cd ..
install:
  - sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf"
  - sudo ldconfig
  - make build
script:
  - make test_coverage
go:
  - 1.6.2
after_success:
  - bash <(curl -s https://codecov.io/bash)
